### ISSUE TITLE
为 Hexo 主题 indigo 添加 gitment 支持

### ISSUE THREAD

**Issue by ckyOL** [ckyOL/ckyOL.github.io#7]
https://blog.ckyol.moe/2017/05/04/gitmentHexoTheme/

**Comment by liukangxu** [comment]
Good job!

**Comment by iljyya** [comment]
我的 ejs 应该都加对了，但是 hexo s 还是报错
```
INFO  Start processing
ERROR Theme config load failed.
ERROR Process failed: _config.yml
    at generateError (C:\blog\node_modules\js-yaml\lib\js-yaml\loader.js:162:10)
    at throwError (C:\blog\node_modules\js-yaml\lib\js-yaml\loader.js:168:9) 
.........
```
是主题配置的不对吗？
```
# 开启
gitment:
  owner: 1464125
  repo: comments
  client_id: f851449a81bef86857ac
  client_secret: 6f3ce61b5e4f9518a13640a35773e5371a575898
```

**Comment by ckyOL** [comment]
@iljyya 配置里的 owner 是github用户名，不是ID

**Comment by iljyya** [comment]
嗯呢，用户名试了还是这样，可能还是哪里不对

**Comment by ckyOL** [comment]
我这插件已经合并到主题最新release，是否更新最新？或者检查customers id之类github app设定

**Comment by fantasykai** [comment]
请教下 ，我这里配置好后， 在博客到评论区，直接显示 Error: Comments Not Initialized 点login就回到首页了～ 大概是哪里点问题撒

**Comment by ckyOL** [comment]
@fantasykai Not initialized 是 gitment 的问题，其依托 GitHub issue 系统。issue 是要创建的，gitment 不会自动创建，因此要自己手动点下 initialize。至于跳转，使用最新版且没自行改动过代码的话应该不会出问题

**Comment by ckyOL** [comment]
@fantasykai 最近迁移至VPS，添加https支援后复现你的问题，应为 github apps 里 Authorization callback URL 错误引起
